//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strana.Revit.HoleTask {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Confing : global::System.Configuration.ApplicationSettingsBase {
        
        private static Confing defaultInstance = ((Confing)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Confing())));
        
        public static Confing Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\sb-sharegp\\StranaDev_FamilyManager\\430_Задания на отверстия\\(Отв_Задание)_Перек" +
            "рытия_Прямоугольное.rfa")]
        public string floorHoleTaskPath {
            get {
                return ((string)(this["floorHoleTaskPath"]));
            }
            set {
                this["floorHoleTaskPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\sb-sharegp\\StranaDev_FamilyManager\\430_Задания на отверстия\\(Отв_Задание)_Стены" +
            "_Прямоугольное.rfa")]
        public string wallHoleTaskPath {
            get {
                return ((string)(this["wallHoleTaskPath"]));
            }
            set {
                this["wallHoleTaskPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int offSetJoin {
            get {
                return ((int)(this["offSetJoin"]));
            }
            set {
                this["offSetJoin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string revitLinks {
            get {
                return ((string)(this["revitLinks"]));
            }
            set {
                this["revitLinks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool areJoin {
            get {
                return ((bool)(this["areJoin"]));
            }
            set {
                this["areJoin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool arePickUpElements {
            get {
                return ((bool)(this["arePickUpElements"]));
            }
            set {
                this["arePickUpElements"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int offSetHoleTask {
            get {
                return ((int)(this["offSetHoleTask"]));
            }
            set {
                this["offSetHoleTask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int roundHoleTaskDimensions {
            get {
                return ((int)(this["roundHoleTaskDimensions"]));
            }
            set {
                this["roundHoleTaskDimensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int roundHoleTaskInPlane {
            get {
                return ((int)(this["roundHoleTaskInPlane"]));
            }
            set {
                this["roundHoleTaskInPlane"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool areRoundHoleTaskInPlane {
            get {
                return ((bool)(this["areRoundHoleTaskInPlane"]));
            }
            set {
                this["areRoundHoleTaskInPlane"] = value;
            }
        }
    }
}
